server:
  port: 9001

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.126.110.110:3306/elements?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: test
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    host: smtp.qq.com
    username: 766564616@qq.com
    password: qxyxlvxmkhjzbbcb
    properties:
      mail:
        smtp:
          auth: true
          timeout: 25000
          ssl:
            enable: true
        starttls:
          enable: true
          required: true
  freemarker:
    charset: UTF-8
    cache: true
    suffix: .html
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
